### ISSUE TITLE
Dutch Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/nl.reactjs.org#1]
## Maintainers List
- @Keraito 
- @jochenboesmans 
- @rickbeerendonk
- @ronderksen
- @timlogemann 
- @degeens 
- @Jacco 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@Keraito) #17 
* [ ] Tutorial (@supermooshman) #29

### Basics

* [x] Hello World (@jochenboesmans) #10
* [x] Introducing JSX (@ronderksen) #11 
* [x] Rendering Elements (@ronderksen) #13
* [x] Components and Props (@ronderksen) #16
* [ ] State and Lifecycle (@Keraito)
* [x] Handling Events (@jochenboesmans) #19
* [x] Conditional Rendering (@jochenboesmans) #21
* [ ] Lists and Keys (@ronderksen) #26
* [ ] Forms (@jochenboesmans) #27
* [ ] Lifting State Up (@jochenboesmans) #30 
* [ ] Composition vs Inheritance (@nickooms) #32 
* [ ] Thinking in React (@Jacco) #43

### API Reference

* [ ] React (@Jacco) #71 
* [ ] React.Component (@Jacco) #72 
* [ ] ReactDOM (@regdot)
* [ ] ReactDOMServer (@regdot)
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started @joranquinten 
* [ ] Add React to a Website @joranquinten #34
* [ ] Create a New React App
* [ ] CDN Links

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks (@Jacco) #44 
  * [ ] Hooks at a Glance (@Jacco) #65 
  * [ ] Using the State Hook (@Jacco) #68 
  * [ ] Using the Effect Hook (@Jacco) #69 
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks (@Jacco)
  * [ ] Hooks API Reference (@Jacco) #70 
  * [ ] Hooks FAQ
### Concurrent Mode

  * [ ] Introducing Concurrent Mode
  * [ ] Suspense for Data Fetching
  * [ ] Concurrent UI Patterns
  * [ ] Adopting Concurrent Mode
  * [ ] Concurrent Mode API Reference

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor (@Jacco) #64 
* [ ] CodeExample (@Jacco) #64 
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by ronderksen** [comment]
I will start translating "Introducing JSX". I can't edit the issue description yet, so a comment will have to do for now :).

**Comment by supermooshman** [comment]
tutorial

**Comment by nickooms** [comment]
Composition vs Inheritance

**Comment by joranquinten** [comment]
I can work on the introduction part! 🇳🇱

**Comment by degeens** [comment]
Is this project still being maintained? I see that a lot of good translations are not reviewed yet.

**Comment by Keraito** [comment]
> Is this project still being maintained? I see that a lot of good translations are not reviewed yet.

@degeens Activity has definitely decreased over time, but feel free to help out and also review other people's translations.

**Comment by tesseralis** [comment]
@Keraito do you need any help with additional maintainers? If so, @degeens would you be interested?

**Comment by degeens** [comment]
> @Keraito do you need any help with additional maintainers? If so, @degeens would you be interested?

I'm definitely interested. We should really get the open pull requests done. :muscle:

**Comment by tesseralis** [comment]
Sure! Just make a PR to https://github.com/reactjs/reactjs.org-translations and edit the file langs/nl.json with your username, and if @Keraito or one of the other maintainers approve you can get started!

**Comment by Jacco** [comment]
Am working on the hooks sections

**Comment by Keraito** [comment]
@Jacco Please specify which chapter you're working on specifically. We want to give everyone equal chance and content for participating, which means we divide it on a chapter basis rather than section 😄

**Comment by Jacco** [comment]
@Keraito hi. No problem :-) I have started to work on most of the Hook sections already but I can easily split the work up in separate PRs.I’ll start from the top. The first 3 or 4 are almost done. If someone else wants to do another part I will not create a PR for those. For consistency in choice of words it can be an issue though. 

Regards Jacco

**Comment by Jacco** [comment]
I volunteered to be maintainer too.

https://github.com/reactjs/reactjs.org-translation/pull/131

@Keraito @degeens can you approve?

**Comment by Jacco** [comment]
I want to claim "Thinking in React" too :-)

**Comment by Jacco** [comment]
Claiming API reference React.

**Comment by Jacco** [comment]
@Keraito @degeens about 

[reactjs/reactjs.org-translation#131](reactjs/reactjs.org-translation#131)

I saw another PR merged without @tesseralis being around. Maybe one of you has been granted write access to that repo?

**Comment by degeens** [comment]
> @Keraito @degeens about
> 
> [reactjs/reactjs.org-translation#131](reactjs/reactjs.org-translation#131)
> 
> I saw another PR merged without @tesseralis being around. Maybe one of you has been granted write access to that repo?

You're right, I merged your PR.

**Comment by regdot** [comment]
I would like to claim React.Component as a start

**Comment by Jacco** [comment]
@regdot don't bother. Project is abandoned. I have tried to get it back on the rails but can't get enough assistance and permissions to do so.

**Comment by Jacco** [comment]
@regdot and I also worked on Component already

**Comment by regdot** [comment]
@Jacco Too bad, could you maybe update the list?

**Comment by Jacco** [comment]
@regdot Thats part of the problem :-) I do not have the right permissions to do certain things in this repo.

I think @tesseralis needs to give some permission to me to get this project going again.

At least I think so because @degeens and @Keraito did not seem to be able to do that.

Those are the only people I saw around when I came to this project.

**Comment by degeens** [comment]
@regdot @Jacco Can you tell me what you've been working on, so I can update the list?

@Jacco Still haven't heard from @tesseralis?

**Comment by rickbeerendonk** [comment]
@Jacco If you go to this page, can you request to join? https://github.com/orgs/reactjs/teams/reactjs-org-localization/members

If so, I can add you to the team.

**Comment by regdot** [comment]
@degeens Nothing so far, need to claim an empty spot :)

@rickbeerendonk I'm getting a 404 error, was this expected?

**Comment by Jacco** [comment]
@degeens not a word :-S

@rickbeerendonk the link does not work. I see you are in the list of 138 member but see no button to request to be invited.

**Comment by tesseralis** [comment]
Hi everyone! I’m sorry for the very late delay. @Jacco, I've just invited you to the React organization and once you confirm, you should be a maintainer. Again, apologies for letting this slip.

**Comment by Jacco** [comment]
Thanks! :-)

**Comment by Jacco** [comment]
@tesseralis 

Finally got the approved hooks intro merged :-)

[https://nl.reactjs.org/docs/hooks-intro.html](https://nl.reactjs.org/docs/hooks-intro.html)

Also got started on the last sync PR, is it necessary to do only the last one? Or do all have to be checked and merged?

**Comment by tesseralis** [comment]
@Jacco thank you so much! Only the most recent one needs to be merged. The rest are duplicates (I haven't gotten around to making it so that it closes old PRs).

**Comment by Jacco** [comment]
@tesseralis Great :-) Now I resolved the merge issues with the latest sync. Need one more approver. Can you do that?

**Comment by Jacco** [comment]
@regdot I updated the things I have been working on

**Comment by regdot** [comment]
@Jacco Thanks, I'll take a good look at it

**Comment by Jacco** [comment]
> @Jacco Thanks, I'll take a good look at it

@regdot Shall I put ReactDOM on your name? We need to work top to bottom somewhat. Let me know what you want to work on.

**Comment by regdot** [comment]
@Jacco I'll take ReactDOM and ReactDOMServer

**Comment by Jacco** [comment]
> @Jacco I'll take ReactDOM and ReactDOMServer

@regdot you might want to wait until a the last sync request is merged. Hope it is soon. All conflicts are removed from it. Just need one more approver. @Keraito @degeens

**Comment by Jacco** [comment]
@regdot please add no extra linefeeds to the file you work on

**Comment by Keraito** [comment]
@Jacco Please keep the number of commits to Github limited if possible. We've already gone through half of the free Netlify plan for this project. Try to keep WIP local, since I saw a few PRs with over 6 builds cuz of WIP commits.

**Comment by Jacco** [comment]
@Keraito netlify doesn't work anyhow all tests are failing. On reactjs.org it is even removed. Keeping on local is bad practice ;-) Commit often!

**Comment by Keraito** [comment]
@Jacco As far as I can see the Netlify uploads are still working, but if it's not used anyways I can just remove it. I definitely agree with committing often, but it's not always needed to push single commits rather than a batch of them 😄 But that doesn't matter anymore if I remove Netlify

**Comment by Jacco** [comment]
@Keraito can you remove both netlify deploys I couldn't find the original one from nl.reactjs.org?

You can see it failing in all new commits since syncing succeeded. Maybe it can be fixed but I don't know how :-)

You can see an example of it failing in #27

**Comment by Jacco** [comment]
@regdot I do not know if you already started, but I found a stale branch on my laptop of the reference-react-dom-server page.  I didn't see this one earlier. You can see the PR.

**Comment by regdot** [comment]
@Jacco I've already started but thanks for the heads up.

**Comment by lextoc** [comment]
I'd like to translate **Advanced Guides - Accessibility**.

**Comment by lextoc** [comment]
-> https://github.com/reactjs/nl.reactjs.org/pull/155

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
