### ISSUE TITLE
Formalities

### ISSUE THREAD

**Issue by Keraito** [reactjs/nl.reactjs.org#2]
So now that we have our repo (🎉!), let's decide on some formal rules before we get into translating áll the stuff. Deciding on and documenting them should hopefully make both the processes now as well as in the future go way smoother 😄. 

## Todos ✔️ 
- [ ] Cleanup some of the repo (I saw some crowdin stuff in the README).
- [ ] Do you guys prefer to communicate through Github or do we want to set up a Discord/Slack/Spectrum for easier communication?

## Translation Rules 📝 
- [ ] [As described here](https://github.com/reactjs/reactjs.org-translation#make-a-glossary-and-style-guide), we should make a glossary and/or style guide consisting of terms which we either do or do not want to translate and if so, how they are translated to make it consistent. We should probably do this in a way that is easy to extend/change it and discuss about those proposals. Personally, a MD file of some sort where we discuss in PRs is fine for me. For the initial batch, we could make an exception for this to make it go smoother.
- [ ] Is it more important to keep the translation as similar to the original as possible, or is it better to express it naturally in Dutch in cases where it's hard to keep it similar? (I prefer the latter).

## Review Process 🔍 
We should decide on some rules on:
- [ ] How will we review proposals/translations? What will we pay attention to and what not?
- [ ] When will we merge it?
- [ ] Since we're with only 3 people atm, how many approvals is considered mergeable?

## Usefull resources 📘 
- [React translation team](https://github.com/orgs/reactjs/teams/reactjs-org-localization)
- [The original React docs](https://reactjs.org)

There's probably more stuff, but let's stick to this for now as it's already a lot 😺 

(And use all the emojis!)
@jochenboesmans @rickbeerendonk
@reactjs/reactjs-org-dutch-translation

**Comment by rickbeerendonk** [comment]
I'm in 🇵🇦 and rural 🇨🇴 for the next 2 days. I will study all procedures and I'll start picking up translations by Tuesday.

**Comment by jochenboesmans** [comment]
> Do you guys prefer to communicate through Github or do we want to set up a Discord/Slack/Spectrum for easier communication?

A more direct/informal medium of communication would definitely be nice. Personally I would prefer Slack.

> we should make a glossary and/or style guide

As soon as we've put together the initial glossary & style guidelines, I'd put it up in a place that's easy for everyone to see.

> Is it more important to keep the translation as similar to the original as possible, or is it better to express it naturally in Dutch in cases where it's hard to keep it similar? (I prefer the latter).

I think this highly depends on whether the translation still feels natural or not.

**Comment by rickbeerendonk** [comment]
> > Do you guys prefer to communicate through Github or do we want to set up a Discord/Slack/Spectrum for easier communication?
> 
> A more direct/informal medium of communication would definitely be nice. Personally I would prefer Slack.

Slack is best for me too.

> > Is it more important to keep the translation as similar to the original as possible, or is it better to express it naturally in Dutch in cases where it's hard to keep it similar? (I prefer the latter).
> 
> I think this highly depends on whether the translation still feels natural or not.

I have the same preference. Professional React users in Holland might use the English docs anyway. Dutch might be preferred by amateurs and kids in school. So it should feel as natural as possible to them.
